import { dirname } from 'path'
import { fileURLToPath } from 'url'
import { FlatCompat } from '@eslint/eslintrc'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

const compat = new FlatCompat({
  baseDirectory: __dirname,
})

const eslintConfig = [
  // Global ignores — next-env.d.ts is auto-generated by Next.js and must not be linted
  {
    ignores: [
      'node_modules/',
      '.next/',
      'out/',
      'next-env.d.ts',
      // Generated by `npm run db:types` (Supabase). Not hand-edited; not linted.
      'src/types/database.ts',
      '*.config.js',
      '*.config.cjs',
      '*.config.mjs',
    ],
  },
  // Next.js + TypeScript base rules (non-type-aware)
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  // Type-aware rules scoped to src/ TypeScript files only — parserOptions.project
  // only applies to files within the TS project boundary
  {
    files: ['src/**/*.{ts,tsx}'],
    languageOptions: {
      parserOptions: {
        project: './tsconfig.json',
      },
    },
    rules: {
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
      '@typescript-eslint/explicit-function-return-type': 'off',
      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/no-misused-promises': 'error',
      '@typescript-eslint/consistent-type-imports': ['error', { prefer: 'type-imports' }],
      'no-console': ['warn', { allow: ['error', 'warn'] }],
      'prefer-const': 'error',
      'no-var': 'error',
    },
  },
]

export default eslintConfig
