/**
 * AURA-303 — admin property write contract (pure domain logic).
 *
 * Single source of truth for the admin create/update/duplicate shapes consumed by:
 *   - the admin API routes (`src/app/api/admin/properties/**`),
 *   - the admin DAL write functions (`src/dal/properties.dal.ts`),
 *   - the admin property form (`src/components/admin/PropertyForm.tsx`, client-side).
 *
 * PURE TypeScript: NO React, NO Supabase, NO DAL, NO services, NO I/O, NO `server-only`.
 * Every business rule lives here (not in JSX or the route), so handlers/forms never trust
 * raw input and the rules are unit-testable in Node.
 *
 * Locked decisions enforced here:
 *   - D-36 taxonomy (never overload `status`): explicit transaction/market/property/
 *     availability/price-visibility/rental/furnishing enums.
 *   - D-47 / A-05 reference number: configurable prefix (`AUTEX`) + padded sequence;
 *     auto-generated by default; optional admin override; uniqueness mandatory.
 *   - A-06 slug: derived from `title.en`, collision-suffixed, immutable after publish.
 *   - D-09 bedrooms: handled by the publish checklist (see ./publish), not required on a draft.
 *   - D-32 lifecycle: draft → published → archived; no hard delete; no published → draft
 *     (unpublish) in MVP.
 *
 * Publish-readiness (completeness) is NOT enforced here — a draft may be incomplete. It is a
 * separate concern in ./publish, evaluated only at publish time.
 */

import { z } from 'zod'

import {
  AVAILABILITY_STATUSES,
  MARKET_TYPES,
  PROPERTY_TYPES,
  TRANSACTION_TYPES,
} from '@/domain/properties/query'
import { SLUG_MAX_LENGTH, SLUG_PATTERN } from '@/domain/properties/detail'

// --- Taxonomy enums not already exported by ./query (D-36) -----------------------

export const PRICE_VISIBILITIES = ['visible', 'price_on_application'] as const
export const RENTAL_PERIODS = ['yearly', 'monthly', 'weekly', 'daily'] as const
export const FURNISHING_STATUSES = [
  'furnished',
  'semi_furnished',
  'unfurnished',
  'unknown',
] as const
export const PUBLISH_STATUSES = ['draft', 'published', 'archived'] as const
export type PublishStatus = (typeof PUBLISH_STATUSES)[number]

/**
 * Off-plan-only columns. These are displayed and meaningful ONLY when
 * `market_type = 'off_plan'` (D-36) and are rejected on a ready property.
 */
export const OFF_PLAN_FIELDS = [
  'developer_name',
  'handover_date',
  'completion_percentage',
  'down_payment_amount',
  'payment_plan_summary',
] as const

// --- Reference number (D-47 / A-05) ----------------------------------------------

/** Default reference-number prefix (owner decision — AUTEX demo brand). */
export const REFERENCE_NUMBER_PREFIX = 'AUTEX'
/** Sequence is zero-padded to this width (e.g. `AUTEX-00041`). */
const REFERENCE_NUMBER_PAD = 5
/** Accepted admin override shape: uppercase alphanumerics + single hyphens, bounded. */
const REFERENCE_NUMBER_PATTERN = /^[A-Z0-9]+(?:-[A-Z0-9]+)*$/
const REFERENCE_NUMBER_MIN = 3
const REFERENCE_NUMBER_MAX = 40

/**
 * Format an auto reference number from a numeric sequence: `${prefix}-${padded}`.
 * Pure + deterministic; the DAL supplies the next sequence and handles uniqueness retry.
 */
export function formatReferenceNumber(
  sequence: number,
  prefix: string = REFERENCE_NUMBER_PREFIX
): string {
  const padded = String(Math.max(0, Math.trunc(sequence))).padStart(REFERENCE_NUMBER_PAD, '0')
  return `${prefix}-${padded}`
}

/** A validated admin override for the reference number (normalised to uppercase). */
export const referenceNumberOverrideSchema = z
  .string()
  .trim()
  .min(REFERENCE_NUMBER_MIN)
  .max(REFERENCE_NUMBER_MAX)
  .transform((v) => v.toUpperCase())
  .refine((v) => REFERENCE_NUMBER_PATTERN.test(v), {
    message: 'Reference number may contain only letters, numbers, and single hyphens.',
  })

// --- Slug (A-06) -----------------------------------------------------------------

/**
 * Derive a public slug from an English title: lowercase, non-alphanumerics → hyphens,
 * collapsed and trimmed, bounded to SLUG_MAX_LENGTH. Returns `''` when the title yields
 * nothing usable (callers treat that as a validation failure). Pure + deterministic; the
 * DAL appends a numeric suffix on collision (`-2`, `-3`, …).
 */
export function slugifyTitleEn(titleEn: string): string {
  const base = titleEn
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, SLUG_MAX_LENGTH)
    .replace(/-+$/g, '')
  return SLUG_PATTERN.test(base) ? base : ''
}

/**
 * Append a collision suffix to a base slug while staying within SLUG_MAX_LENGTH:
 * `marina-penthouse` → `marina-penthouse-2`. `n <= 1` returns the base unchanged.
 */
export function withSlugSuffix(base: string, n: number): string {
  if (n <= 1) return base
  const suffix = `-${n}`
  const room = SLUG_MAX_LENGTH - suffix.length
  return `${base.slice(0, room).replace(/-+$/g, '')}${suffix}`
}

// --- Lifecycle rules (D-32) ------------------------------------------------------

/** A property can be edited only while it is not archived (archived is terminal in MVP UI). */
export function canEditProperty(status: PublishStatus): boolean {
  return status !== 'archived'
}

/** Publishing is allowed only from `draft` (no re-publish, no unpublish — D-32). */
export function canPublish(status: PublishStatus): boolean {
  return status === 'draft'
}

/** Archiving is allowed from `draft` or `published`; archiving an archived row is a no-op error. */
export function canArchive(status: PublishStatus): boolean {
  return status === 'draft' || status === 'published'
}

/** A-06: the slug may change only while the property is a draft; immutable once published. */
export function canMutateSlug(status: PublishStatus): boolean {
  return status === 'draft'
}

// --- Field schemas ---------------------------------------------------------------

const i18nRequiredEn = z.object({ en: z.string().trim().min(1).max(200) })
const i18nOptionalEn = z
  .object({ en: z.string().trim().max(5000) })
  .partial()
  .optional()

const nonNegInt = z.number().int().nonnegative()
const nonNegNumber = z.number().nonnegative()

/** Editable property columns an admin may set (all optional — the base for create + update). */
const editableShape = {
  title: i18nRequiredEn.optional(),
  description: i18nOptionalEn,
  transaction_type: z.enum(TRANSACTION_TYPES).optional(),
  market_type: z.enum(MARKET_TYPES).optional(),
  property_type: z.enum(PROPERTY_TYPES).optional(),
  availability_status: z.enum(AVAILABILITY_STATUSES).optional(),
  price_visibility: z.enum(PRICE_VISIBILITIES).optional(),
  rental_period: z.enum(RENTAL_PERIODS).nullable().optional(),
  furnishing_status: z.enum(FURNISHING_STATUSES).optional(),
  price: nonNegNumber.nullable().optional(),
  location_label: z.string().trim().min(1).max(200).optional(),
  community: z.string().trim().max(200).nullable().optional(),
  sub_community: z.string().trim().max(200).nullable().optional(),
  building_name: z.string().trim().max(200).nullable().optional(),
  address: z.string().trim().max(500).nullable().optional(),
  external_map_url: z.string().trim().url().max(500).nullable().optional(),
  bedrooms: nonNegInt.nullable().optional(),
  bathrooms: nonNegInt.nullable().optional(),
  parking: nonNegInt.nullable().optional(),
  size_sqft: nonNegNumber.optional(),
  size_sqm: nonNegNumber.nullable().optional(),
  amenities: z.array(z.string().trim().min(1).max(100)).max(100).optional(),
  rera_number: z.string().trim().max(100).nullable().optional(),
  permit_number: z.string().trim().max(100).nullable().optional(),
  agent_name: z.string().trim().max(200).nullable().optional(),
  agent_phone: z.string().trim().max(50).nullable().optional(),
  agent_whatsapp: z.string().trim().max(50).nullable().optional(),
  agent_email: z.string().trim().email().max(200).nullable().optional(),
  developer_name: z.string().trim().max(200).nullable().optional(),
  handover_date: z
    .string()
    .trim()
    .regex(/^\d{4}-\d{2}-\d{2}$/, 'handover_date must be an ISO date (YYYY-MM-DD)')
    .nullable()
    .optional(),
  completion_percentage: z.number().int().min(0).max(100).nullable().optional(),
  down_payment_amount: nonNegNumber.nullable().optional(),
  payment_plan_summary: z.string().trim().max(2000).nullable().optional(),
  is_featured: z.boolean().optional(),
} as const

/**
 * Reject off-plan-only fields on a non-off-plan property (D-36). Runs when `market_type`
 * is known on the payload; the publish checklist re-checks the merged record at publish.
 */
function offPlanRefine(
  value: Record<string, unknown>,
  ctx: z.RefinementCtx,
  marketType: unknown
): void {
  if (marketType !== undefined && marketType !== 'off_plan') {
    for (const field of OFF_PLAN_FIELDS) {
      const v = value[field]
      if (v !== undefined && v !== null && v !== '') {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,
          path: [field],
          message: `${field} is allowed only when market_type is off_plan.`,
        })
      }
    }
  }
}

/** Create a DRAFT property. The minimal required set lets the slug derive and the row insert. */
export const propertyCreateSchema = z
  .object({
    ...editableShape,
    title: i18nRequiredEn,
    transaction_type: z.enum(TRANSACTION_TYPES),
    market_type: z.enum(MARKET_TYPES),
    property_type: z.enum(PROPERTY_TYPES),
    location_label: z.string().trim().min(1).max(200),
    size_sqft: nonNegNumber,
    reference_number: referenceNumberOverrideSchema.optional(),
  })
  .superRefine((value, ctx) => {
    offPlanRefine(value, ctx, value.market_type)
    if (slugifyTitleEn(value.title.en) === '') {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        path: ['title', 'en'],
        message: 'Title must contain letters or numbers so a URL slug can be derived.',
      })
    }
  })

export type PropertyCreateInput = z.infer<typeof propertyCreateSchema>

/**
 * Update an existing property. All editable fields optional; `publish: true` requests a
 * draft → published transition (gated by the publish checklist in the route/DAL). Slug,
 * reference number, publish_status, and ownership columns are intentionally NOT accepted —
 * slug/reference immutability (A-06) and the lifecycle (D-32) are enforced structurally.
 */
export const propertyUpdateSchema = z
  .object({
    ...editableShape,
    publish: z.boolean().optional(),
  })
  .superRefine((value, ctx) => {
    offPlanRefine(value, ctx, value.market_type)
  })

export type PropertyUpdateInput = z.infer<typeof propertyUpdateSchema>

// --- Update payload builder (slug/reference/status immutability backstop) ---------

/** Columns an admin update may NEVER write directly (immutability + lifecycle backstop). */
const NON_UPDATABLE_KEYS = new Set([
  'id',
  'slug',
  'reference_number',
  'publish_status',
  'published_at',
  'archived_at',
  'title_en',
  'views_count',
  'created_at',
  'created_by',
  'updated_at',
  'publish',
])

/**
 * Build the DB update object for a property: the provided editable fields only, with
 * `updated_by` stamped. Defensively strips any immutable/lifecycle key (slug, reference
 * number, publish_status, …) even if present — so slug can never change via update (A-06)
 * and the publish lifecycle cannot be driven through the generic patch.
 */
export function buildUpdatePayload(
  patch: Record<string, unknown>,
  actorUserId: string | null
): Record<string, unknown> {
  const out: Record<string, unknown> = {}
  for (const [key, value] of Object.entries(patch)) {
    if (NON_UPDATABLE_KEYS.has(key)) continue
    if (value === undefined) continue
    out[key] = value
  }
  out.updated_by = actorUserId
  return out
}

// --- Duplicate projection (API_SPEC: copy editable fields, new slug/reference, draft) ---

/** The source columns the duplicate reads (admin projection subset). */
export interface DuplicateSourceRow {
  title: unknown
  description: unknown
  transaction_type: string
  market_type: string
  property_type: string
  availability_status: string
  price_visibility: string
  rental_period: string | null
  furnishing_status: string
  price: number | null
  location_label: string
  community: string | null
  sub_community: string | null
  building_name: string | null
  address: string | null
  external_map_url: string | null
  bedrooms: number | null
  bathrooms: number | null
  parking: number | null
  size_sqft: number
  size_sqm: number | null
  amenities: unknown
  rera_number: string | null
  permit_number: string | null
  agent_name: string | null
  agent_phone: string | null
  agent_whatsapp: string | null
  agent_email: string | null
  developer_name: string | null
  handover_date: string | null
  completion_percentage: number | null
  down_payment_amount: number | null
  payment_plan_summary: string | null
  is_featured: boolean
}

/**
 * Project a source property into a DRAFT duplicate insert: copy editable fields, attach the
 * caller-supplied new `slug` + `reference_number`, force `publish_status='draft'`, and DO NOT
 * copy `id`, timestamps, `published_at`/`archived_at`, or `views_count` (API_SPEC). The new
 * row is never featured by default to avoid surfacing an unfinished duplicate.
 */
export function buildDuplicateInsert(
  source: DuplicateSourceRow,
  args: { slug: string; reference_number: string; actorUserId: string | null }
): Record<string, unknown> {
  return {
    title: source.title,
    description: source.description,
    transaction_type: source.transaction_type,
    market_type: source.market_type,
    property_type: source.property_type,
    availability_status: source.availability_status,
    price_visibility: source.price_visibility,
    rental_period: source.rental_period,
    furnishing_status: source.furnishing_status,
    price: source.price,
    location_label: source.location_label,
    community: source.community,
    sub_community: source.sub_community,
    building_name: source.building_name,
    address: source.address,
    external_map_url: source.external_map_url,
    bedrooms: source.bedrooms,
    bathrooms: source.bathrooms,
    parking: source.parking,
    size_sqft: source.size_sqft,
    size_sqm: source.size_sqm,
    amenities: source.amenities,
    rera_number: source.rera_number,
    permit_number: source.permit_number,
    agent_name: source.agent_name,
    agent_phone: source.agent_phone,
    agent_whatsapp: source.agent_whatsapp,
    agent_email: source.agent_email,
    developer_name: source.developer_name,
    handover_date: source.handover_date,
    completion_percentage: source.completion_percentage,
    down_payment_amount: source.down_payment_amount,
    payment_plan_summary: source.payment_plan_summary,
    is_featured: false,
    slug: args.slug,
    reference_number: args.reference_number,
    publish_status: 'draft',
    created_by: args.actorUserId,
    updated_by: args.actorUserId,
  }
}
